# -*- coding: utf-8 -*-
"""Pathway.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/140jaRSA4mBi2AX6uROpvzVSMn42FP4eD
"""

pip install cobra

from cobra import Model,Reaction,Metabolite
import cobra

pathway = Model('Pathway')

dpg_c13 = Metabolite(
  'dpg_c13'
, formula='C3H4O10P2', 
 name='3-Phospho-D-glyceroyl phosphate', 
 compartment='c')

pg_c2 = Metabolite(
  'pg_c2'
, formula='C3H4O7P', 
 name='D-Glycerate 2-phosphate', 
 compartment='c')

pg_c3 = Metabolite(
  'pg_c3'
, formula='C3H4O7P', 
 name='3-Phospho-D-glycerate', 
 compartment='c')

pgc_c6 = Metabolite(
  'pgc_c6'
, formula='C6H10O10P', 
 name='6-Phospho-D-gluconate', 
 compartment='c')

pgl_c6 = Metabolite(
  'pgl_c6'
, formula='C6H9O9P', 
 name='6-phospho-D-glucono-1,5-lactone', 
 compartment='c')

ac_c = Metabolite(
  'ac_c'
, formula='C2H3O2', 
 name='Acetate', 
 compartment='c')

ac_e = Metabolite(
  'ac_e'
, formula='C2H3O2', 
 name='Acetate', 
 compartment='e')

acald_c = Metabolite(
  'acald_c'
, formula='C2H4O', 
 name='Acetaldehyde', 
 compartment='c')

acald_e = Metabolite(
  'acald_e'
, formula='C2H4O', 
 name='Acetaldehyde', 
 compartment='e')

accoa_c = Metabolite(
  'accoa_c'
, formula='C23H34N7O17P3S', 
 name='Acetyl-CoA', 
 compartment='c')

acon_C_c = Metabolite(
  'acon_C_c'
, formula='C6H3O6', 
 name='Cis-Aconitate', 
 compartment='c')

actp_c = Metabolite(
  'actp_c'
, formula='C2H3O5P', 
 name='Acetyl phosphate', 
 compartment='c')

adp_c = Metabolite(
  'adp_c'
, formula='C10H12N5O10P2', 
 name='ADP C10H12N5O10P2', 
 compartment='c')

akg_c = Metabolite(
  'akg_c'
, formula='C5H4O5', 
 name='2-Oxoglutarate', 
 compartment='c')

akg_e = Metabolite(
  'akg_e'
, formula='C5H4O5', 
 name='2-Oxoglutarate', 
 compartment='e')

amp_c = Metabolite(
  'amp_c'
, formula='C10H12N5O7P', 
 name='AMP C10H12N5O7P', 
 compartment='c')

atp_c = Metabolite(
  'atp_c'
, formula='C10H12N5O13P3', 
 name='ATP C10H12N5O13P3', 
 compartment='c')

cit_c = Metabolite(
  'cit_c'
, formula='C6H5O7', 
 name='Citrate', 
 compartment='c')

co2_c = Metabolite(
  'co2_c'
, formula='CO2', 
 name='CO2 CO2', 
 compartment='c')

co2_e = Metabolite(
  'co2_e'
, formula='CO2', 
 name='CO2 CO2', 
 compartment='e')

coa_c = Metabolite(
  'coa_c'
, formula='C21H32N7O16P3S', 
 name='Coenzyme A', 
 compartment='c')

dhap_c = Metabolite(
  'dhap_c'
, formula='C3H5O6P', 
 name='Dihydroxyacetone phosphate', 
 compartment='c')

e4p_c = Metabolite(
  'e4p_c'
, formula='C4H7O7P', 
 name='D-Erythrose 4-phosphate', 
 compartment='c')

etoh_c = Metabolite(
  'etoh_c'
, formula='C2H6O', 
 name='Ethanol', 
 compartment='c')

etoh_e = Metabolite(
  'etoh_e'
, formula='C2H6O', 
 name='Ethanol', 
 compartment='e')

f6p_c = Metabolite(
  'f6p_c'
, formula='C6H11O9P', 
 name='D-Fructose 6-phosphate', 
 compartment='c')

fdp_c = Metabolite(
  'fdp_c'
, formula='C6H10O12P2', 
 name='D-Fructose 1,6-bisphosphate', 
 compartment='c')

for_c = Metabolite(
  'for_c'
, formula='CH1O2', 
 name='Formate', 
 compartment='c')

for_e = Metabolite(
  'for_e'
, formula='CH1O2', 
 name='Formate', 
 compartment='e')

fru_e = Metabolite(
  'fru_e'
, formula='C6H12O6', 
 name='D-Fructose', 
 compartment='e')

fum_c = Metabolite(
  'fum_c'
, formula='C4H2O4', 
 name='Fumarate', 
 compartment='c')

fum_e = Metabolite(
  'fum_e'
, formula='C4H2O4', 
 name='Fumarate', 
 compartment='e')

g3p_c = Metabolite(
  'g3p_c'
, formula='C3H5O6P', 
 name='Glyceraldehyde 3-phosphate', 
 compartment='c')

g6p_c = Metabolite(
  'g6p_c'
, formula='C6H11O9P', 
 name='D-Glucose 6-phosphate', 
 compartment='c')

glc__D_e = Metabolite(
  'glc__D_e'
, formula='C6H12O6', 
 name='D-Glucose', 
 compartment='e')

gln__L_c = Metabolite(
  'gln__L_c'
, formula='C5H10N2O3', 
 name='L-Glutamine', 
 compartment='c')

gln__L_e = Metabolite(
  'gln__L_e'
, formula='C5H10N2O3', 
 name='L-Glutamine', 
 compartment='e')

glu__L_c = Metabolite(
  'glu__L_c'
, formula='C5H8NO4', 
 name='L-Glutamate', 
 compartment='c')

glu__L_e = Metabolite(
  'glu__L_e'
, formula='C5H8NO4', 
 name='L-Glutamate', 
 compartment='e')

glx_c = Metabolite(
  'glx_c'
, formula='C2H1O3', 
 name='Glyoxylate', 
 compartment='c')

h2o_c = Metabolite(
  'h2o_c'
, formula='H2O', 
 name='H2O H2O', 
 compartment='c')

h2o_e = Metabolite(
  'h2o_e'
, formula='H2O', 
 name='H2O H2O', 
 compartment='e')

h_c = Metabolite(
  'h_c'
, formula='H', 
 name='H+', 
 compartment='c')

h_e = Metabolite(
  'h_e'
, formula='H', 
 name='H+', 
 compartment='e')

icit_c = Metabolite(
  'icit_c'
, formula='C6H5O7', 
 name='Isocitrate', 
 compartment='c')

lac__D_c = Metabolite(
  'lac__D_c'
, formula='C3H5O3', 
 name='D-Lactate', 
 compartment='c')

lac__D_e = Metabolite(
  'lac__D_e'
, formula='C3H5O3', 
 name='D-Lactate', 
 compartment='e')

mal__L_c = Metabolite(
  'mal__L_c'
, formula='C4H4O5', 
 name='L-Malate', 
 compartment='c')

mal__L_e = Metabolite(
  'mal__L_e'
, formula='C4H4O5', 
 name='L-Malate', 
 compartment='e')

nad_c = Metabolite(
  'nad_c'
, formula='C21H26N7O14P2', 
 name='Nicotinamide adenine dinucleotide', 
 compartment='c')

nadh_c = Metabolite(
  'nadh_c'
, formula='C21H27N7O14P2', 
 name='Nicotinamide adenine dinucleotide - reduced', 
 compartment='c')

nadp_c = Metabolite(
  'nadp_c'
, formula='C21H25N7O17P3', 
 name='Nicotinamide adenine dinucleotide phosphate', 
 compartment='c')

nadph_c = Metabolite(
  'nadph_c'
, formula='C21H26N7O17P3', 
 name='Nicotinamide adenine dinucleotide phosphate - reduced', 
 compartment='c')

nh4_c = Metabolite(
  'nh4_c'
, formula='H4N', 
 name='Ammonium', 
 compartment='c')

nh4_e = Metabolite(
  'nh4_e'
, formula='H4N', 
 name='Ammonium', 
 compartment='e')

o2_c = Metabolite(
  'o2_c'
, formula='O2', 
 name='O2 O2', 
 compartment='c')

o2_e = Metabolite(
  'o2_e'
, formula='O2', 
 name='O2 O2', 
 compartment='e')

oaa_c = Metabolite(
  'oaa_c'
, formula='C4H2O5', 
 name='Oxaloacetate', 
 compartment='c')

pep_c = Metabolite(
  'pep_c'
, formula='C3H2O6P', 
 name='Phosphoenolpyruvate', 
 compartment='c')

pi_c = Metabolite(
  'pi_c'
, formula='HO4P', 
 name='Phosphate', 
 compartment='c')

pi_e = Metabolite(
  'pi_e'
, formula='HO4P', 
 name='Phosphate', 
 compartment='e')

pyr_c = Metabolite(
  'pyr_c'
, formula='C3H3O3', 
 name='Pyruvate', 
 compartment='c')

pyr_e = Metabolite(
  'pyr_e'
, formula='C3H3O3', 
 name='Pyruvate', 
 compartment='e')

q8_c = Metabolite(
  'q8_c'
, formula='C49H74O4', 
 name='Ubiquinone-8', 
 compartment='c')

q8h2_c = Metabolite(
  'q8h2_c'
, formula='C49H76O4', 
 name='Ubiquinol-8', 
 compartment='c')

r5p_c = Metabolite(
  'r5p_c'
, formula='C5H9O8P', 
 name='Alpha-D-Ribose 5-phosphate', 
 compartment='c')

ru5p__D_c = Metabolite(
  'ru5p__D_c'
, formula='C5H9O8P', 
 name='D-Ribulose 5-phosphate', 
 compartment='c')

s7p_c = Metabolite(
  's7p_c'
, formula='C7H13O10P', 
 name='Sedoheptulose 7-phosphate', 
 compartment='c')

succ_c = Metabolite(
  'succ_c'
, formula='C4H4O4', 
 name='Succinate', 
 compartment='c')

succ_e = Metabolite(
  'succ_e'
, formula='C4H4O4', 
 name='Succinate', 
 compartment='e')

succoa_c = Metabolite(
  'succoa_c'
, formula='C25H35N7O19P3S', 
 name='Succinyl-CoA', 
 compartment='c')

xu5p__D_c = Metabolite(
  'xu5p__D_c'
, formula='C5H9O8P', 
 name='D-Xylulose 5-phosphate', 
 compartment='c')

ACALD = Reaction('ACALD')
ACALD.name = "Acetaldehyde dehydrogenase (acetylating)"
ACALD.lower_bound = -1000
ACALD.upper_bound=1000

ACALDt = Reaction('ACALDt')
ACALDt.name = "Acetaldehyde reversible transport"
ACALDt.lower_bound = -1000
ACALDt.upper_bound=1000

ACKr = Reaction('ACKr')
ACKr.name = "Acetate kinase"
ACKr.lower_bound = -1000
ACKr.upper_bound=1000

ACONTa = Reaction('ACONTa')
ACONTa.name = "Aconitase (half-reaction A, Citrate hydro-lyase)"
ACONTa.lower_bound = -1000
ACONTa.upper_bound=1000

ACONTb = Reaction('ACONTb')
ACONTb.name = "Aconitase (half-reaction B, Isocitrate hydro-lyase)"
ACONTb.lower_bound = -1000
ACONTb.upper_bound=1000

ACt2r = Reaction('ACt2r')
ACt2r.name = "Acetate reversible transport via proton symport"
ACt2r.lower_bound = -1000
ACt2r.upper_bound=1000

ADK1 = Reaction('ADK1')
ADK1.name = "Adenylate kinase"
ADK1.lower_bound = -1000
ADK1.upper_bound=1000

AKGDH = Reaction('AKGDH')
AKGDH.name = "2-Oxogluterate dehydrogenase"
AKGDH.lower_bound = 0
AKGDH.upper_bound=1000

AKGt2r = Reaction('AKGt2r')
AKGt2r.name = "2 oxoglutarate reversible transport via symport"
AKGt2r.lower_bound = -1000
AKGt2r.upper_bound=1000

ALCD2x = Reaction('ALCD2x')
ALCD2x.name = "Alcohol dehydrogenase (ethanol)"
ALCD2x.lower_bound = -1000
ALCD2x.upper_bound=1000

ATPM = Reaction('ATPM')
ATPM.name = "ATP maintenance requirement"
ATPM.lower_bound = 8.39
ATPM.upper_bound=1000

ATPS4r = Reaction('ATPS4r')
ATPS4r.name = "ATP synthase (four protons for one ATP)"
ATPS4r.lower_bound = -1000
ATPS4r.upper_bound=1000

BIOMASS_Ecoli_core_w_GAM = Reaction('BIOMASS_Ecoli_core_w_GAM')
BIOMASS_Ecoli_core_w_GAM.name = "Biomass Objective Function with GAM"
BIOMASS_Ecoli_core_w_GAM.lower_bound = 0
BIOMASS_Ecoli_core_w_GAM.upper_bound=1000

CO2t = Reaction('CO2t')
CO2t.name = "CO2 transporter via diffusion"
CO2t.lower_bound = -1000
CO2t.upper_bound=1000

CS = Reaction('CS')
CS.name = "Citrate synthase"
CS.lower_bound = 0
CS.upper_bound=1000

CYTBD = Reaction('CYTBD')
CYTBD.name = "Cytochrome oxidase bd (ubiquinol-8: 2 protons)"
CYTBD.lower_bound = 0
CYTBD.upper_bound=1000

D_LACt2 = Reaction('D_LACt2')
D_LACt2.name = "D lactate transport via proton symport"
D_LACt2.lower_bound = -1000
D_LACt2.upper_bound=1000

ENO = Reaction('ENO')
ENO.name = "Enolase"
ENO.lower_bound = -1000
ENO.upper_bound=1000

ETOHt2r = Reaction('ETOHt2r')
ETOHt2r.name = "Ethanol reversible transport via proton symport"
ETOHt2r.lower_bound = -1000
ETOHt2r.upper_bound=1000

EX_ac_e = Reaction('EX_ac_e')
EX_ac_e.name = "Acetate exchange"
EX_ac_e.lower_bound = 0
EX_ac_e.upper_bound=1000

EX_acald_e = Reaction('EX_acald_e')
EX_acald_e.name = "Acetaldehyde exchange"
EX_acald_e.lower_bound = 0
EX_acald_e.upper_bound=1000

EX_akg_e = Reaction('EX_akg_e')
EX_akg_e.name = "2-Oxoglutarate exchange"
EX_akg_e.lower_bound = 0
EX_akg_e.upper_bound=1000

EX_co2_e = Reaction('EX_co2_e')
EX_co2_e.name = "CO2 exchange"
EX_co2_e.lower_bound = -1000
EX_co2_e.upper_bound=1000

EX_etoh_e = Reaction('EX_etoh_e')
EX_etoh_e.name = "Ethanol exchange"
EX_etoh_e.lower_bound = 0
EX_etoh_e.upper_bound=1000

EX_for_e = Reaction('EX_for_e')
EX_for_e.name = "Formate exchange"
EX_for_e.lower_bound = 0
EX_for_e.upper_bound=1000

EX_fru_e = Reaction('EX_fru_e')
EX_fru_e.name = "D-Fructose exchange"
EX_fru_e.lower_bound = 0
EX_fru_e.upper_bound=1000

EX_fum_e = Reaction('EX_fum_e')
EX_fum_e.name = "Fumarate exchange"
EX_fum_e.lower_bound = 0
EX_fum_e.upper_bound=1000

EX_glc__D_e = Reaction('EX_glc__D_e')
EX_glc__D_e.name = "D-Glucose exchange"
EX_glc__D_e.lower_bound = -10
EX_glc__D_e.upper_bound=1000

EX_gln__L_e = Reaction('EX_gln__L_e')
EX_gln__L_e.name = "L-Glutamine exchange"
EX_gln__L_e.lower_bound = 0
EX_gln__L_e.upper_bound=1000

EX_glu__L_e = Reaction('EX_glu__L_e')
EX_glu__L_e.name = "L-Glutamate exchange"
EX_glu__L_e.lower_bound = 0
EX_glu__L_e.upper_bound=1000

EX_h_e = Reaction('EX_h_e')
EX_h_e.name = "H+ exchange"
EX_h_e.lower_bound = -1000
EX_h_e.upper_bound=1000

EX_h2o_e = Reaction('EX_h2o_e')
EX_h2o_e.name = "H2O exchange"
EX_h2o_e.lower_bound = -1000
EX_h2o_e.upper_bound=1000

EX_lac__D_e = Reaction('EX_lac__D_e')
EX_lac__D_e.name = "D-lactate exchange"
EX_lac__D_e.lower_bound = 0
EX_lac__D_e.upper_bound=1000

EX_mal__L_e = Reaction('EX_mal__L_e')
EX_mal__L_e.name = "L-Malate exchange"
EX_mal__L_e.lower_bound = 0
EX_mal__L_e.upper_bound=1000

EX_nh4_e = Reaction('EX_nh4_e')
EX_nh4_e.name = "Ammonia exchange"
EX_nh4_e.lower_bound = -1000
EX_nh4_e.upper_bound=1000

EX_o2_e = Reaction('EX_o2_e')
EX_o2_e.name = "O2 exchange"
EX_o2_e.lower_bound = -1000
EX_o2_e.upper_bound=1000

EX_pi_e = Reaction('EX_pi_e')
EX_pi_e.name = "Phosphate exchange"
EX_pi_e.lower_bound = -1000
EX_pi_e.upper_bound=1000

EX_pyr_e = Reaction('EX_pyr_e')
EX_pyr_e.name = "Pyruvate exchange"
EX_pyr_e.lower_bound = 0
EX_pyr_e.upper_bound=1000

EX_succ_e = Reaction('EX_succ_e')
EX_succ_e.name = "Succinate exchange"
EX_succ_e.lower_bound = 0
EX_succ_e.upper_bound=1000

FBA = Reaction('FBA')
FBA.name = "Fructose-bisphosphate aldolase"
FBA.lower_bound = -1000
FBA.upper_bound=1000

FBP = Reaction('FBP')
FBP.name = "Fructose-bisphosphatase"
FBP.lower_bound = 0
FBP.upper_bound=1000

FORt2 = Reaction('FORt2')
FORt2.name = "Formate transport in via proton symport"
FORt2.lower_bound = 0
FORt2.upper_bound=1000

FORt = Reaction('FORt')
FORt.name = "Formate transport via diffusion"
FORt.lower_bound = -1000
FORt.upper_bound=0

FRD7 = Reaction('FRD7')
FRD7.name = "Fumarate reductase"
FRD7.lower_bound = 0
FRD7.upper_bound=1000

FRUpts2 = Reaction('FRUpts2')
FRUpts2.name = "Fructose transport via PEP:Pyr PTS (f6p generating)"
FRUpts2.lower_bound = 0
FRUpts2.upper_bound=1000

FUM = Reaction('FUM')
FUM.name = "Fumarase"
FUM.lower_bound = -1000
FUM.upper_bound=1000

FUMt2_2 = Reaction('FUMt2_2')
FUMt2_2.name = "Fumarate transport via proton symport (2 H)"
FUMt2_2.lower_bound = 0
FUMt2_2.upper_bound=1000

G6PDH2r = Reaction('G6PDH2r')
G6PDH2r.name = "Glucose 6-phosphate dehydrogenase"
G6PDH2r.lower_bound = -1000
G6PDH2r.upper_bound=1000

GAPD = Reaction('GAPD')
GAPD.name = "Glyceraldehyde-3-phosphate dehydrogenase"
GAPD.lower_bound = -1000
GAPD.upper_bound=1000

GLCpts = Reaction('GLCpts')
GLCpts.name = "D-glucose transport via PEP:Pyr PTS"
GLCpts.lower_bound = 0
GLCpts.upper_bound=1000

GLNS = Reaction('GLNS')
GLNS.name = "Glutamine synthetase"
GLNS.lower_bound = 0
GLNS.upper_bound=1000

GLNabc = Reaction('GLNabc')
GLNabc.name = "L-glutamine transport via ABC system"
GLNabc.lower_bound = 0
GLNabc.upper_bound=1000

GLUDy = Reaction('GLUDy')
GLUDy.name = "Glutamate dehydrogenase (NADP)"
GLUDy.lower_bound = -1000
GLUDy.upper_bound=1000

GLUN = Reaction('GLUN')
GLUN.name = "Glutaminase"
GLUN.lower_bound = 0
GLUN.upper_bound=1000

GLUSy = Reaction('GLUSy')
GLUSy.name = "Glutamate synthase (NADPH)"
GLUSy.lower_bound = 0
GLUSy.upper_bound=1000

GLUt2r = Reaction('GLUt2r')
GLUt2r.name = "L glutamate transport via proton symport  reversible"
GLUt2r.lower_bound = -1000
GLUt2r.upper_bound=1000

GND = Reaction('GND')
GND.name = "Phosphogluconate dehydrogenase"
GND.lower_bound = 0
GND.upper_bound=1000

H2Ot = Reaction('H2Ot')
H2Ot.name = "H2O transport via diffusion"
H2Ot.lower_bound = -1000
H2Ot.upper_bound=1000

ICDHyr = Reaction('ICDHyr')
ICDHyr.name = "Isocitrate dehydrogenase (NADP)"
ICDHyr.lower_bound = -1000
ICDHyr.upper_bound=1000

ICL = Reaction('ICL')
ICL.name = "Isocitrate lyase"
ICL.lower_bound = 0
ICL.upper_bound=1000

LDH_D = Reaction('LDH_D')
LDH_D.name = "D-lactate dehydrogenase"
LDH_D.lower_bound = -1000
LDH_D.upper_bound=1000

MALS = Reaction('MALS')
MALS.name = "Malate synthase"
MALS.lower_bound = 0
MALS.upper_bound=1000

MALt2_2 = Reaction('MALt2_2')
MALt2_2.name = "Malate transport via proton symport (2 H)"
MALt2_2.lower_bound = 0
MALt2_2.upper_bound=1000

MDH = Reaction('MDH')
MDH.name = "Malate dehydrogenase"
MDH.lower_bound = -1000
MDH.upper_bound=1000

ME1 = Reaction('ME1')
ME1.name = "Malic enzyme (NAD)"
ME1.lower_bound = 0
ME1.upper_bound=1000

ME2 = Reaction('ME2')
ME2.name = "Malic enzyme (NADP)"
ME2.lower_bound = 0
ME2.upper_bound=1000

NADH16 = Reaction('NADH16')
NADH16.name = "NADH dehydrogenase (ubiquinone-8 & 3 protons)"
NADH16.lower_bound = 0
NADH16.upper_bound=1000

NADTRHD = Reaction('NADTRHD')
NADTRHD.name = "NAD transhydrogenase"
NADTRHD.lower_bound = 0
NADTRHD.upper_bound=1000

NH4t = Reaction('NH4t')
NH4t.name = "Ammonia reversible transport"
NH4t.lower_bound = -1000
NH4t.upper_bound=1000

O2t = Reaction('O2t')
O2t.name = "O2 transport  diffusion "
O2t.lower_bound = -1000
O2t.upper_bound=1000

PDH = Reaction('PDH')
PDH.name = "Pyruvate dehydrogenase"
PDH.lower_bound = 0
PDH.upper_bound=1000

PFK = Reaction('PFK')
PFK.name = "Phosphofructokinase"
PFK.lower_bound = 0
PFK.upper_bound=1000

PFL = Reaction('PFL')
PFL.name = "Pyruvate formate lyase"
PFL.lower_bound = 0
PFL.upper_bound=1000

PGI = Reaction('PGI')
PGI.name = "Glucose-6-phosphate isomerase"
PGI.lower_bound = -1000
PGI.upper_bound=1000

PGK = Reaction('PGK')
PGK.name = "Phosphoglycerate kinase"
PGK.lower_bound = -1000
PGK.upper_bound=1000

PGL = Reaction('PGL')
PGL.name = "6-phosphogluconolactonase"
PGL.lower_bound = 0
PGL.upper_bound=1000

PGM = Reaction('PGM')
PGM.name = "Phosphoglycerate mutase"
PGM.lower_bound = -1000
PGM.upper_bound=1000

PIt2r = Reaction('PIt2r')
PIt2r.name = "Phosphate reversible transport via symport"
PIt2r.lower_bound = -1000
PIt2r.upper_bound=1000

PPC = Reaction('PPC')
PPC.name = "Phosphoenolpyruvate carboxylase"
PPC.lower_bound = 0
PPC.upper_bound=1000

PPCK = Reaction('PPCK')
PPCK.name = "Phosphoenolpyruvate carboxykinase"
PPCK.lower_bound = 0
PPCK.upper_bound=1000

PPS = Reaction('PPS')
PPS.name = "Phosphoenolpyruvate synthase"
PPS.lower_bound = 0
PPS.upper_bound=1000

PTAr = Reaction('PTAr')
PTAr.name = "Phosphotransacetylase"
PTAr.lower_bound = -1000
PTAr.upper_bound=1000

PYK = Reaction('PYK')
PYK.name = "Pyruvate kinase"
PYK.lower_bound = 0
PYK.upper_bound=1000

PYRt2 = Reaction('PYRt2')
PYRt2.name = "Pyruvate transport in via proton symport"
PYRt2.lower_bound = -1000
PYRt2.upper_bound=1000

RPE = Reaction('RPE')
RPE.name = "Ribulose 5-phosphate 3-epimerase"
RPE.lower_bound = -1000
RPE.upper_bound=1000

RPI = Reaction('RPI')
RPI.name = "Ribose-5-phosphate isomerase"
RPI.lower_bound = -1000
RPI.upper_bound=1000

SUCCt2_2 = Reaction('SUCCt2_2')
SUCCt2_2.name = "Succinate transport via proton symport (2 H)"
SUCCt2_2.lower_bound = 0
SUCCt2_2.upper_bound=1000

SUCCt3 = Reaction('SUCCt3')
SUCCt3.name = "Succinate transport out via proton antiport"
SUCCt3.lower_bound = 0
SUCCt3.upper_bound=1000

SUCDi = Reaction('SUCDi')
SUCDi.name = "Succinate dehydrogenase (irreversible)"
SUCDi.lower_bound = 0
SUCDi.upper_bound=1000

SUCOAS = Reaction('SUCOAS')
SUCOAS.name = "Succinyl-CoA synthetase (ADP-forming)"
SUCOAS.lower_bound = -1000
SUCOAS.upper_bound=1000

TALA = Reaction('TALA')
TALA.name = "Transaldolase"
TALA.lower_bound = -1000
TALA.upper_bound=1000

THD2 = Reaction('THD2')
THD2.name = "NAD(P) transhydrogenase"
THD2.lower_bound = 0
THD2.upper_bound=1000

TKT1 = Reaction('TKT1')
TKT1.name = "Transketolase"
TKT1.lower_bound = -1000
TKT1.upper_bound=1000

TKT2 = Reaction('TKT2')
TKT2.name = "Transketolase"
TKT2.lower_bound = -1000
TKT2.upper_bound=1000

TPI = Reaction('TPI')
TPI.name = "Triose-phosphate isomerase"
TPI.lower_bound = -1000
TPI.upper_bound=1000

ACALD.add_metabolites({ 
acald_c:-1 , 
accoa_c:1 , 
coa_c:-1 , 
h_c:1 , 
nad_c:-1 , 
nadh_c:1 ,
})
ACALDt.add_metabolites({ 
acald_c:1 , 
acald_e:-1 ,
})
ACKr.add_metabolites({ 
ac_c:-1 , 
actp_c:1 , 
adp_c:1 , 
atp_c:-1 ,
})
ACONTa.add_metabolites({ 
acon_C_c:1 , 
cit_c:-1 , 
h2o_c:1 ,
})
ACONTb.add_metabolites({ 
acon_C_c:-1 , 
h2o_c:-1 , 
icit_c:1 ,
})
ACt2r.add_metabolites({ 
ac_c:1 , 
ac_e:-1 , 
h_c:1 , 
h_e:-1 ,
})
ADK1.add_metabolites({ 
adp_c:2 , 
amp_c:-1 , 
atp_c:-1 ,
})
AKGDH.add_metabolites({ 
akg_c:-1 , 
co2_c:1 , 
coa_c:-1 , 
nad_c:-1 , 
nadh_c:1 , 
succoa_c:1 ,
})
AKGt2r.add_metabolites({ 
akg_c:1 , 
akg_e:-1 , 
h_c:1 , 
h_e:-1 ,
})
ALCD2x.add_metabolites({ 
acald_c:1 , 
etoh_c:-1 , 
h_c:1 , 
nad_c:-1 , 
nadh_c:1 ,
})
ATPM.add_metabolites({ 
adp_c:1 , 
atp_c:-1 , 
h2o_c:-1 , 
h_c:1 , 
pi_c:1 ,
})
ATPS4r.add_metabolites({ 
adp_c:-1 , 
atp_c:1 , 
h2o_c:1 , 
h_c:3 , 
h_e:-4 , 
pi_c:-1 ,
})
BIOMASS_Ecoli_core_w_GAM.add_metabolites({ 
pg_c3:-1.496 , 
accoa_c:-3.7478 , 
adp_c:59.81 , 
akg_c:4.1182 , 
atp_c:-59.81 , 
coa_c:3.7478 , 
e4p_c:-0.361 , 
f6p_c:-0.0709 , 
g3p_c:-0.129 , 
g6p_c:-0.205 , 
gln__L_c:-0.2557 , 
glu__L_c:-4.9414 , 
h2o_c:-59.81 , 
h_c:59.81 , 
nad_c:-3.547 , 
nadh_c:3.547 , 
nadp_c:13.0279 , 
nadph_c:-13.0279 , 
oaa_c:-1.7867 , 
pep_c:-0.5191 , 
pi_c:59.81 , 
pyr_c:-2.8328 , 
r5p_c:-0.8977 ,
})
CO2t.add_metabolites({ 
co2_c:1 , 
co2_e:-1 ,
})
CS.add_metabolites({ 
accoa_c:-1 , 
cit_c:1 , 
coa_c:1 , 
h2o_c:-1 , 
h_c:1 , 
oaa_c:-1 ,
})
CYTBD.add_metabolites({ 
h2o_c:1 , 
h_c:-2 , 
h_e:2 , 
o2_c:-0.5 , 
q8_c:1 , 
q8h2_c:-1 ,
})
D_LACt2.add_metabolites({ 
h_c:1 , 
h_e:-1 , 
lac__D_c:1 , 
lac__D_e:-1 ,
})
ENO.add_metabolites({ 
pg_c2:-1 , 
h2o_c:1 , 
pep_c:1 ,
})
ETOHt2r.add_metabolites({ 
etoh_c:1 , 
etoh_e:-1 , 
h_c:1 , 
h_e:-1 ,
})
EX_ac_e.add_metabolites({ 
ac_e:-1 ,
})
EX_acald_e.add_metabolites({ 
acald_e:-1 ,
})
EX_akg_e.add_metabolites({ 
akg_e:-1 ,
})
EX_co2_e.add_metabolites({ 
co2_e:-1 ,
})
EX_etoh_e.add_metabolites({ 
etoh_e:-1 ,
})
EX_for_e.add_metabolites({ 
for_e:-1 ,
})
EX_fru_e.add_metabolites({ 
fru_e:-1 ,
})
EX_fum_e.add_metabolites({ 
fum_e:-1 ,
})
EX_glc__D_e.add_metabolites({ 
glc__D_e:-1 ,
})
EX_gln__L_e.add_metabolites({ 
gln__L_e:-1 ,
})
EX_glu__L_e.add_metabolites({ 
glu__L_e:-1 ,
})
EX_h_e.add_metabolites({ 
h_e:-1 ,
})
EX_h2o_e.add_metabolites({ 
h2o_e:-1 ,
})
EX_lac__D_e.add_metabolites({ 
lac__D_e:-1 ,
})
EX_mal__L_e.add_metabolites({ 
mal__L_e:-1 ,
})
EX_nh4_e.add_metabolites({ 
nh4_e:-1 ,
})
EX_o2_e.add_metabolites({ 
o2_e:-1 ,
})
EX_pi_e.add_metabolites({ 
pi_e:-1 ,
})
EX_pyr_e.add_metabolites({ 
pyr_e:-1 ,
})
EX_succ_e.add_metabolites({ 
succ_e:-1 ,
})
FBA.add_metabolites({ 
dhap_c:1 , 
fdp_c:-1 , 
g3p_c:1 ,
})
FBP.add_metabolites({ 
f6p_c:1 , 
fdp_c:-1 , 
h2o_c:-1 , 
pi_c:1 ,
})
FORt2.add_metabolites({ 
for_c:1 , 
for_e:-1 , 
h_c:1 , 
h_e:-1 ,
})
FORt.add_metabolites({ 
for_c:1 , 
for_e:-1 ,
})
FRD7.add_metabolites({ 
fum_c:-1 , 
q8_c:1 , 
q8h2_c:-1 , 
succ_c:1 ,
})
FRUpts2.add_metabolites({ 
f6p_c:1 , 
fru_e:-1 , 
pep_c:-1 , 
pyr_c:1 ,
})
FUM.add_metabolites({ 
fum_c:-1 , 
h2o_c:-1 , 
mal__L_c:1 ,
})
FUMt2_2.add_metabolites({ 
fum_c:1 , 
fum_e:-1 , 
h_c:2 , 
h_e:-2 ,
})
G6PDH2r.add_metabolites({ 
pgl_c6:1 , 
g6p_c:-1 , 
h_c:1 , 
nadp_c:-1 , 
nadph_c:1 ,
})
GAPD.add_metabolites({ 
dpg_c13:1 , 
g3p_c:-1 , 
h_c:1 , 
nad_c:-1 , 
nadh_c:1 , 
pi_c:-1 ,
})
GLCpts.add_metabolites({ 
g6p_c:1 , 
glc__D_e:-1 , 
pep_c:-1 , 
pyr_c:1 ,
})
GLNS.add_metabolites({ 
adp_c:1 , 
atp_c:-1 , 
gln__L_c:1 , 
glu__L_c:-1 , 
h_c:1 , 
nh4_c:-1 , 
pi_c:1 ,
})
GLNabc.add_metabolites({ 
adp_c:1 , 
atp_c:-1 , 
gln__L_c:1 , 
gln__L_e:-1 , 
h2o_c:-1 , 
h_c:1 , 
pi_c:1 ,
})
GLUDy.add_metabolites({ 
akg_c:1 , 
glu__L_c:-1 , 
h2o_c:-1 , 
h_c:1 , 
nadp_c:-1 , 
nadph_c:1 , 
nh4_c:1 ,
})
GLUN.add_metabolites({ 
gln__L_c:-1 , 
glu__L_c:1 , 
h2o_c:-1 , 
nh4_c:1 ,
})
GLUSy.add_metabolites({ 
akg_c:-1 , 
gln__L_c:-1 , 
glu__L_c:2 , 
h_c:-1 , 
nadp_c:1 , 
nadph_c:-1 ,
})
GLUt2r.add_metabolites({ 
glu__L_c:1 , 
glu__L_e:-1 , 
h_c:1 , 
h_e:-1 ,
})
GND.add_metabolites({ 
pgc_c6:-1 , 
co2_c:1 , 
nadp_c:-1 , 
nadph_c:1 , 
ru5p__D_c:1 ,
})
H2Ot.add_metabolites({ 
h2o_c:1 , 
h2o_e:-1 ,
})
ICDHyr.add_metabolites({ 
akg_c:1 , 
co2_c:1 , 
icit_c:-1 , 
nadp_c:-1 , 
nadph_c:1 ,
})
ICL.add_metabolites({ 
glx_c:1 , 
icit_c:-1 , 
succ_c:1 ,
})
LDH_D.add_metabolites({ 
h_c:1 , 
lac__D_c:-1 , 
nad_c:-1 , 
nadh_c:1 , 
pyr_c:1 ,
})
MALS.add_metabolites({ 
accoa_c:-1 , 
coa_c:1 , 
glx_c:-1 , 
h2o_c:-1 , 
h_c:1 , 
mal__L_c:1 ,
})
MALt2_2.add_metabolites({ 
h_c:2 , 
h_e:-2 , 
mal__L_c:1 , 
mal__L_e:-1 ,
})
MDH.add_metabolites({ 
h_c:1 , 
mal__L_c:-1 , 
nad_c:-1 , 
nadh_c:1 , 
oaa_c:1 ,
})
ME1.add_metabolites({ 
co2_c:1 , 
mal__L_c:-1 , 
nad_c:-1 , 
nadh_c:1 , 
pyr_c:1 ,
})
ME2.add_metabolites({ 
co2_c:1 , 
mal__L_c:-1 , 
nadp_c:-1 , 
nadph_c:1 , 
pyr_c:1 ,
})
NADH16.add_metabolites({ 
h_c:-4 , 
h_e:3 , 
nad_c:1 , 
nadh_c:-1 , 
q8_c:-1 , 
q8h2_c:1 ,
})
NADTRHD.add_metabolites({ 
nad_c:-1 , 
nadh_c:1 , 
nadp_c:1 , 
nadph_c:-1 ,
})
NH4t.add_metabolites({ 
nh4_c:1 , 
nh4_e:-1 ,
})
O2t.add_metabolites({ 
o2_c:1 , 
o2_e:-1 ,
})
PDH.add_metabolites({ 
accoa_c:1 , 
co2_c:1 , 
coa_c:-1 , 
nad_c:-1 , 
nadh_c:1 , 
pyr_c:-1 ,
})
PFK.add_metabolites({ 
adp_c:1 , 
atp_c:-1 , 
f6p_c:-1 , 
fdp_c:1 , 
h_c:1 ,
})
PFL.add_metabolites({ 
accoa_c:1 , 
coa_c:-1 , 
for_c:1 , 
pyr_c:-1 ,
})
PGI.add_metabolites({ 
f6p_c:1 , 
g6p_c:-1 ,
})
PGK.add_metabolites({ 
dpg_c13:1 , 
pg_c3:-1 , 
adp_c:1 , 
atp_c:-1 ,
})
PGL.add_metabolites({ 
pgc_c6:1 , 
pgl_c6:-1 , 
h2o_c:-1 , 
h_c:1 ,
})
PGM.add_metabolites({ 
pg_c2:-1 , 
pg_c3:1 ,
})
PIt2r.add_metabolites({ 
h_c:1 , 
h_e:-1 , 
pi_c:1 , 
pi_e:-1 ,
})
PPC.add_metabolites({ 
co2_c:-1 , 
h2o_c:-1 , 
h_c:1 , 
oaa_c:1 , 
pep_c:-1 , 
pi_c:1 ,
})
PPCK.add_metabolites({ 
adp_c:1 , 
atp_c:-1 , 
co2_c:1 , 
oaa_c:-1 , 
pep_c:1 ,
})
PPS.add_metabolites({ 
amp_c:1 , 
atp_c:-1 , 
h2o_c:-1 , 
h_c:2 , 
pep_c:1 , 
pi_c:1 , 
pyr_c:-1 ,
})
PTAr.add_metabolites({ 
accoa_c:-1 , 
actp_c:1 , 
coa_c:1 , 
pi_c:-1 ,
})
PYK.add_metabolites({ 
adp_c:-1 , 
atp_c:1 , 
h_c:-1 , 
pep_c:-1 , 
pyr_c:1 ,
})
PYRt2.add_metabolites({ 
h_c:1 , 
h_e:-1 , 
pyr_c:1 , 
pyr_e:-1 ,
})
RPE.add_metabolites({ 
ru5p__D_c:-1 , 
xu5p__D_c:1 ,
})
RPI.add_metabolites({ 
r5p_c:-1 , 
ru5p__D_c:1 ,
})
SUCCt2_2.add_metabolites({ 
h_c:2 , 
h_e:-2 , 
succ_c:1 , 
succ_e:-1 ,
})
SUCCt3.add_metabolites({ 
h_c:1 , 
h_e:-1 , 
succ_c:-1 , 
succ_e:1 ,
})
SUCDi.add_metabolites({ 
fum_c:1 , 
q8_c:-1 , 
q8h2_c:1 , 
succ_c:-1 ,
})
SUCOAS.add_metabolites({ 
adp_c:1 , 
atp_c:-1 , 
coa_c:-1 , 
pi_c:1 , 
succ_c:-1 , 
succoa_c:1 ,
})
TALA.add_metabolites({ 
e4p_c:1 , 
f6p_c:1 , 
g3p_c:-1 , 
s7p_c:-1 ,
})
THD2.add_metabolites({ 
h_c:2 , 
h_e:-2 , 
nad_c:1 , 
nadh_c:-1 , 
nadp_c:-1 , 
nadph_c:1 ,
})
TKT1.add_metabolites({ 
g3p_c:1 , 
r5p_c:-1 , 
s7p_c:1 , 
xu5p__D_c:-1 ,
})
TKT2.add_metabolites({ 
e4p_c:-1 , 
f6p_c:1 , 
g3p_c:1 , 
xu5p__D_c:-1 ,
})
TPI.add_metabolites({ 
dhap_c:-1 , 
g3p_c:1 ,
})

pathway.add_reactions([ ACALD,ACALDt,ACKr,ACONTa,ACONTb,ACt2r,ADK1,AKGDH,AKGt2r,ALCD2x,ATPM,ATPS4r,BIOMASS_Ecoli_core_w_GAM,CO2t,CS,CYTBD,D_LACt2,ENO,ETOHt2r,EX_ac_e,EX_acald_e,EX_akg_e,EX_co2_e,EX_etoh_e,EX_for_e,EX_fru_e,EX_fum_e,EX_glc__D_e,EX_gln__L_e,EX_glu__L_e,EX_h_e,EX_h2o_e,EX_lac__D_e,EX_mal__L_e,EX_nh4_e,EX_o2_e,EX_pi_e,EX_pyr_e,EX_succ_e,FBA,FBP,FORt2,FORt,FRD7,FRUpts2,FUM,FUMt2_2,G6PDH2r,GAPD,GLCpts,GLNS,GLNabc,GLUDy,GLUN,GLUSy,GLUt2r,GND,H2Ot,ICDHyr,ICL,LDH_D,MALS,MALt2_2,MDH,ME1,ME2,NADH16,NADTRHD,NH4t,O2t,PDH,PFK,PFL,PGI,PGK,PGL,PGM,PIt2r,PPC,PPCK,PPS,PTAr,PYK,PYRt2,RPE,RPI,SUCCt2_2,SUCCt3,SUCDi,SUCOAS,TALA,THD2,TKT1,TKT2,TPI])

pathway.objective = 'BIOMASS_Ecoli_core_w_GAM'
pathway.optimize()

cobra.io.save_json_model(pathway, "pathway.json")

